name: pocketbase_offline_cache
description: A starting point for Dart libraries or applications.
version: 0.2.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.0

dependencies:
  logger: ^2.0.0
  http: ^1.0.0
  flutter:
    sdk: flutter
  path: ^1.0.0
  path_provider: ^2.0.0
  pocketbase: ^0.19.0
  sqlite3: ^2.0.0
  sqlite3_flutter_libs: ^0.5.0
  state_groups: ^0.5.0
  synchronized: ^3.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  dart_lints:
    git:
      url: https://gitlab.com/azuredown/dart-lints.git
      ref: main
